---
id: adm
url: "https://www.adm-immo.com/fr/liste.htm#page=1&TypeModeListeForm=text&ope=1&filtre=8"
linksRegExp: detail
referenceRegExp: "<span itemprop=\"productID\">([0-9]{5,})<\/span>"
contentSelector: '#content'