---
id: cabinethyvrard
url: https://www.cabinethyvrard.fr/vente/
waitFor: .description
waitUntil: networkidle0
linksRegExp: property
referenceRegExp: "<p class=\"reference\">Réf : ([0-9]{4,})<\/p>"
hashLinks: true