---
id: efficity
url: "https://www.efficity.com/achat-immobilier/results/?inputed_location=Saint-Chamond&property_type=2&max_price=&min_nb_of_rooms=1"
linksRegExp: maison_
referenceRegExp: "\/house\/([0-9]+)\/"