---
id: liberation24
url: http://www.liberation24immo.com/recherche/?offre=vente&type=3&prix_min&prix_max&code_postal&departement%5B0%5D=42&reference
linksRegExp: biens\/
referenceRegExp: "class=\"ref\">([0-9]{3,})"
contentSelector: "#maincontent"