---
id: notaires
url: https://www.immobilier.notaires.fr/fr/annonces-immobilieres-liste?typeBien=MAI&typeTransaction=VENTE,VNI,VAE&localite=564,18576,18455,18634,18637,18605&page=1&parPage=12
linksRegExp: vente\/maison\/
referenceRegExp: "<div class=\"ref hidden-xs ng-binding\">Réf.&nbsp;: (.*)"
waitUntil: networkidle0