---
id: propriete-privee
url: "https://www.proprietes-privees.com/annonces-immobilieres?tradePrestation=&location=42400+SAINT-CHAMOND&region=&department=&city=28146&type%5B%5D=maison&nb_pieces=&salePrice%5B%5D=&salePrice%5B%5D="
linksRegExp: ASA$
referenceRegExp: "<strong>Ref. : ([0-9A-Z]{6,})<\/strong>"